services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "15173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/dist
    networks:
      - wizbee
    restart: always
    environment:
      - TZ=Asia/Seoul

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "18080"
      - "19090"
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
    environment:
      SERVER_PORT: 18080
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SOCKETIO_SERVER_HOSTNAME: "0.0.0.0"
      SOCKETIO_SERVER_PORT: 19090
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 16379
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
      TZ: Asia/Seoul
      JAVA_SECURITY_PROPERTIES: 
        jdk.internal.reflect.permitAll=true
        jdk.reflect.allowNativeAccess=true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - wizbee
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  mysql:
    build: ./mysql
    container_name: mysql
    expose:
      - "13306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wizbee
    restart: always

  redis:
    build: ./redis
    container_name: redis
    expose:
      - "16379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/var/run/redis:/var/run/redis
      - redis_data:/data
    networks:
      - wizbee

volumes:
  mysql_data:
  mysql_pid:
  redis_data:
  redis_pid:

networks:
  wizbee:
    external: true