services:
  mysql:
    build: 
      context: ./mysql
    container_name: mysql
    expose:
      - "13306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    restart: always

  redis:
    build: ./redis
    container_name: redis
    expose:
      - "16379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/var/run/redis:/var/run/redis
      - redis_data:/data
    networks:
      - app_network

volumes:
  mysql_data:
  mysql_pid:
  redis_data:
  redis_pid:

networks:
  app_network:
    external: true